### PR TITLE
Enh: Redis cache for expensive SQL queries

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Review by alexsosic — CHANGES_REQUESTED** [review]
I think you're missing `aioredis` in the `install_requires` of `setup.py`

**Comment by tranchitella** [comment]
@alexsosic thanks, good spot, (force) pushed the fix: we also need hiredis.

**Comment by alexsosic** [comment]
Not working inside the C4.
`INFO:     192.168.160.7:50522 - "POST /kamailio/routing HTTP/1.1" 500 Internal Server Error`
Also `--debug` flag not working, confd is crashing when given that flag.

**Comment by fredericlepied** [comment]
recheck

**Comment by tranchitella** [comment]
recheck

**Comment by tranchitella** [comment]
> Not working inside the C4.
> `INFO: 192.168.160.7:50522 - "POST /kamailio/routing HTTP/1.1" 500 Internal Server Error`
> Also `--debug` flag not working, confd is crashing when given that flag.

This has been fixed with cache invalidation. Now tests fail on zuul while they pass locally, trying to run them again, let's see what happens...

**Review by alexsosic — APPROVED** [review]

**Pull request merged**
