### PR TITLE
aiopg, asynchronous connection to PostgreSQL for kamailio end-points

### PR DESCRIPTION
**Pull request by tranchitella**
Use aiopg to query the PostgreSQL database in end-points used by Kamailio.

### CODE REVIEW

**Review by sileht — COMMENTED** [review]
Did you try aiopg.sa to keep the benefit of sqlalchemy datatype conversion ?
Or you just want to have less layer as possible ?

**Review by alexsosic — APPROVED** [review]

**Comment by alexsosic** [comment]
Tested locally with repo tests and with c4 tests inside c4. Running stress-tests now.

**Comment by tranchitella** [comment]
> Did you try aiopg.sa to keep the benefit of sqlalchemy datatype conversion ?
> Or you just want to have less layer as possible ?

@sileht we want to exactly control the SQL query in order to achieve maximum performances in C4.

**Comment by sileht** [comment]
recheck

**Review by sileht — APPROVED** [review]

**Pull request merged**
