### PR TITLE
Requirements aligned to debian buster, improved openapi definition

### PR DESCRIPTION
**Pull request by tranchitella**

### CODE REVIEW

**Review by alexsosic — APPROVED** [review]
Tested with confd tests and in integration with c4 on docker-compose. Everything seems working.

**Comment by alexsosic** [comment]
Also please note there is a slightly **DECREASE IN PERFORMANCE** during the stress tests. I'm having some calls now failing at 300cps which WAS NOT THE CASE before!

**Comment by tranchitella** [comment]
@sboily @sileht your opinion?

**Comment by tranchitella** [comment]
@alexsosic reported the decrease in performances is linked to rtpengine and not the API.

**Review by pc-m — APPROVED** [review]

**Pull request merged**
