### PR TITLE
[WAZO-1564] add PAI in json response

### PR DESCRIPTION
**Pull request by mwolff44**

### CODE REVIEW

**Comment by mwolff44** [comment]
@pcm thanks

**Comment by pc-m** [comment]
> Build failed.
> 
> * [wazo-c4-docker-build-test ](https://zuul.wazo.community/logs/38/38/b022ca773cec79c93c49b73ddfc4d484bc37a3e1/check/wazo-c4-docker-build-test/012e55a/) : SUCCESS in 18m 06s
> * [tox-linters ](https://zuul.wazo.community/logs/38/38/b022ca773cec79c93c49b73ddfc4d484bc37a3e1/check/tox-linters/1299f84/) : FAILURE in 7m 54s
> * [wazo-tox-py37 ](https://zuul.wazo.community/logs/38/38/b022ca773cec79c93c49b73ddfc4d484bc37a3e1/check/wazo-tox-py37/0efef25/) : SUCCESS in 9m 14s
> * [debian-packaging ](https://zuul.wazo.community/logs/38/38/b022ca773cec79c93c49b73ddfc4d484bc37a3e1/check/debian-packaging/99c2c3c/) : FAILURE in 5m 50s

MyPy is still complaining because we are concatenating strings with variables that can be None
 
```python
                                "extra": "P-Asserted-Identity: <sip:"
                                + request.from_name
                                + "@"
                                + normalized_from_uri
                                + ">\r\n",
```

request.from_name is an optional string, you need to handle that case here because str + None + str is not valid

**Comment by mwolff44** [comment]
but this variables can't be None. Where it gets that ?

**Comment by pc-m** [comment]
> but this variables can't be None. Where it gets that ?

In practice I don't know if it's possible to have no from_name but the model specifies that it is optional

```python
class RoutingRequest(BaseModel):
    event: Optional[str] = None
    auth: bool = False
    source_ip: Optional[str] = None
    source_port: Optional[int] = None
    domain: Optional[str] = None
    username: Optional[str] = None
    call_id: Optional[str] = None
    from_name: Optional[str] = None
    from_uri: str
    from_tag: Optional[str] = None
    to_uri: str
    to_name: Optional[str] = None
    to_tag: Optional[str] = None
```

If it's impossible the `from_name` could be `str` instead of `Optional[str]`

**Review by pc-m — DISMISSED** [review]

**Review by pc-m — APPROVED** [review]

**Comment by pc-m** [comment]
I rebased the branch against master and re-approved the PR. Zuul should be happy and merge it now.

**Pull request merged**
