### PR TITLE
zuul.yaml: add c4-docker-build-test-template

### PR DESCRIPTION
**Pull request by fredericlepied**
Depends-On: https://github.com/wazo-platform/sf-jobs/pull/36
Depends-On: https://github.com/wazo-platform/wazo-c4/pull/2

### CODE REVIEW

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Comment by fredericlepied** [comment]
recheck

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
