### PR TITLE
tests: run them using postgresql instead of sqlite

### PR DESCRIPTION
**Pull request by sileht**
## tests: run them using postgresql instead of sqlite

sqlite have many limitation (e.g.: no foreign key check) and driver data
type maybe different between postgresql and sqlite.

This change uses postgresql instead of sqlite.

pifpaf is used to spawn a temporary postgresql database.

TODO:

[] Replace pifpaf by spawn a docker container.

## alembic: fixup initial state

The initial revision of alembic migration script was not in correct
order.

This change fix it and add a test for verify migration scripts generate
same database as the described model.

## Enh: use pytest fixtures to set up test database

The only running test is:

$ pytest wazo_router_confd/tests/test_api_carriers.py

## zuul: use vm template

Depends-On: https://github.com/wazo-platform/sf-jobs/pull/31

### CODE REVIEW

**Comment by sileht** [comment]
recheck

**Comment by sileht** [comment]
recheck

**Review by tranchitella — DISMISSED** [review]
Great work!

**Comment by sileht** [comment]
[WAZO-1179]

[WAZO-1179]: https://wazo-dev.atlassian.net/browse/WAZO-1179

**Comment by sileht** [comment]
recheck

**Review by tranchitella — APPROVED** [review]

**Pull request merged**
