### PR TITLE
Dependencies fix to test Zuul migration

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
Won't fix

```
FAILED tests/test_did_ok-failover.py::test_did_ok_failover - assert 1 == 0
FAILED tests/test_did_ok-failover_within_dialog.py::test_did_ok_failover_within_dialog
FAILED tests/test_domain_ok-failover.py::test_domain_ok_failover - assert 1 == 0
FAILED tests/test_domain_ok-failover_within_dialog.py::test_domain_ok_failover_within_dialog
FAILED tests/test_outbound_ok-failover.py::test_outbound_ok_failover - assert...
FAILED tests/test_outbound_ok-failover_within_dialog.py::test_outbound_ok_failover_within_dialog
```

Should be fixed for other jobs

```
Traceback (most recent call last):
  File "<stdin>", line 102, in <module>
  File "<stdin>", line 94, in _ansiballz_main
  File "<stdin>", line 40, in invoke_module
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_tox_install_sibling_packages_payload__hccuF/ansible_tox_install_sibling_packages_payload.zip/ansible/modules/tox_install_sibling_packages.py", line 23, in <module>
ImportError: No module named pkg_resources
```

Done working on the CI migration for this repository, leaving PR open as it might be useful

**Comment by sduthil** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
recheck

**Comment by rgarrigue** [comment]
Closing to clean up my dangling PR list

**Pull request closed without merging**
